In [4]:
import numpy as np

In [25]:
a = np.array([[20,25,20]])
b = np.array([[10,50,5]])

In [28]:
(a * b).T                                                                                            # T is for Transform

array([[ 200],
       [1250],
       [ 100]])

In [33]:
# Subtracting 2 Vectors

a.T - b.T

array([[ 10],
       [-25],
       [ 15]])

In [80]:
# Dot product of 2 vectors
# For 2-D vectors,it is the equivalent to matrix multiplication.

u = np.array([10,25])
v = np.array([2,5])

np.dot(u,v)

145

### Scaler Addition

In [67]:
a = 2
u = np.array([[30,15]])

a * u

array([[60, 30]])

### Matrix Addition, Subtraction

In [79]:
a = np.array([[12,18],[5,2],[25,32]])
b = np.array([[10,7],[25,3],[14,15]])

print(f"{a} = a \n\n")
print(f"{b} = b \n\n")

a + b

[[12 18]
 [ 5  2]
 [25 32]] = a 


[[10  7]
 [25  3]
 [14 15]] = b 




array([[22, 25],
       [30,  5],
       [39, 47]])

### Matrix Scaler Multiplication

In [69]:
a = np.array([[2,5],[6,8],[9,1]])
u = 2

a * 2

array([[ 4, 10],
       [12, 16],
       [18,  2]])

### Matrix & Vector Multiplication

In [74]:
a = [[5,10],[-15,20]]
b = [10,12]

np.dot(a,b)

array([170,  90])

### Matrix & Matrix Multiplication

In [77]:
a = [[5,10], [15,20], [25,30]]
b = [[3,6], [9,5]]

np.dot(a, b)

array([[105,  80],
       [225, 190],
       [345, 300]])

### Transpose a Matrix

In [83]:
a = np.array([[10,20],[20,50],[40,80]])
print(a, end=" = a \n\n")
print(a.T, end = " = aT")

[[10 20]
 [20 50]
 [40 80]] = a 

[[10 20 40]
 [20 50 80]] = aT

### Create an Identity Matrix

In [90]:
I1 = np.eye(2)
I2 = np.eye(3)

print(I1, end=" = I1 \n\n")
print(I2, end=" = I2 \n\n")

[[1. 0.]
 [0. 1.]] = I1 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2 



In [93]:
### Inverse a Matrix
##### Given a square matrix A
##### , return the matrix ainv satisfying dot(a, ainv)
##### = dot(ainv, a) = eye(a.shape[0]).

a = np.array([
    [2, 1, 0],
    [0, 1, 0],
    [1, 2, 1],
])
print(a, end=" = a\n\n")
print(np.linalg.inv(a), end=" = |a|")
      

[[2 1 0]
 [0 1 0]
 [1 2 1]] = a

[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] = |a|