In [4]:
import numpy as np

In [25]:
a = np.array([[20,25,20]])
b = np.array([[10,50,5]])

In [28]:
(a * b).T                                                                                            # T is for Transform

array([[ 200],
       [1250],
       [ 100]])

In [33]:
# Subtracting 2 Vectors

a.T - b.T

array([[ 10],
       [-25],
       [ 15]])

In [38]:
# Dot product of 2 vectors
# For 2-D vectors,it is the equivalent to matrix multiplication.

u = np.array([10,25])
v = np.array([2,5])

np.dot(u,v)

145

In [54]:
a = np.array([[12,18],[5,2],[25,32]])
b = np.array([[10,7],[25,3],[14,15]])

print(f"{a} = a \n\n")
print(f"{b} = b \n\n")

a * b

[[12 18]
 [ 5  2]
 [25 32]] = a 


[[10  7]
 [25  3]
 [14 15]] = b 




array([[120, 126],
       [125,   6],
       [350, 480]])